apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-api
  namespace: argocd
  labels:
    app: sample-api
    team: platform
    managed-by: app-of-apps
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: applications

  source:
    repoURL: https://github.com/vishwassharma98499/kubestack-ref.git
    targetRevision: HEAD
    path: kubernetes/apps/sample-api

  destination:
    server: https://kubernetes.default.svc
    namespace: app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - Validate=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Health checks — ArgoCD uses these to determine if the app is healthy
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas  # Ignore replica count diff caused by HPA
