apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-api
  namespace: app
  labels:
    app: sample-api
    team: platform
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: api.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sample-api
                port:
                  number: 80
